# Generated by Django 4.0.4 on 2022-05-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=60, verbose_name='Nama Lengkap')),
                ('alamat', models.CharField(max_length=300)),
                ('noktp', models.CharField(max_length=20, verbose_name='Nomor KTP')),
                ('tanggal', models.DateTimeField(verbose_name='Tanggal Booking')),
                ('jam', models.CharField(max_length=20, verbose_name='Jam Booking')),
            ],
        ),
    ]
