# Generated by Django 4.0.4 on 2022-05-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='tanggal',
            field=models.DateField(verbose_name='Tanggal Booking'),
        ),
    ]
